package prob3;

import java.util.function.Function;

public interface MyFunctionWithException<T, R> {
	R apply(T t) throws Exception;
	
	public static <T,R> Function<T, R> wrapper(MyFunctionWithException<T, R> f){
		return x -> {
			try {
				return f.apply(x);
			}catch(Exception e) {
				throw new RuntimeException("Exception thrown");
			}
		};
	}
}
